version: '3.7'
volumes:
  datastore:
services:
  haiku:
    # image: haiku:0.1.0
    build: .
    ports:
      - 3000:3000
    volumes:
      - $PWD/.env:/.env
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - datastore:/data/db
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - datastore:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - datastore:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --lru_mb=2048 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:latest
    ports:
      - 8001:8001
    command: dgraph-ratel
  pulsar:
    image: apachepulsar/pulsar:2.5.2
    command: bin/pulsar standalone
    # hostname: pulsar
    ports:
      - "8082:8082"
      - "6650:6650"
    restart: unless-stopped
    volumes:
      - datastore:/data/db
      # - "./data/:/pulsar/data"
  dashboard:
    image: apachepulsar/pulsar-manager:v0.1.0
    ports:
      - "9527:9527"
    depends_on:
      - pulsar
    links:
      - pulsar
    volumes:
      - datastore:/data
      # - "./data/:/data"
    environment:
      REDIRECT_HOST: "http://127.0.0.1"
      REDIRECT_PORT: "9527"
      DRIVER_CLASS_NAME: "org.postgresql.Driver"
      URL: "jdbc:postgresql://127.0.0.1:5432/pulsar_manager"
      USERNAME: "pulsar"
      PASSWORD: "pulsar"
      LOG_LEVEL: "DEBUG"
