version: '3.7'
services:
  haiku:
    # image: haiku:0.1.0
    build: .
    ports:
      - 3000:3000
    volumes:
      - $PWD/.env:/.env
  mongodb:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: